"""Persisted live-integration evidence (generated by explicit live test commands)."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional

from app.domain.release_status import IntegrationReleaseStatus

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent
ARTIFACTS_DIR = PROJECT_ROOT / "artifacts" / "release"
EVIDENCE_FILE = ARTIFACTS_DIR / "live-evidence.json"


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def load_evidence() -> Dict[str, Any]:
    if not EVIDENCE_FILE.exists():
        return {}
    try:
        return json.loads(EVIDENCE_FILE.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


def save_evidence(data: Dict[str, Any]) -> None:
    ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
    EVIDENCE_FILE.write_text(json.dumps(data, indent=2, sort_keys=True), encoding="utf-8")


def record_live_result(
    component: str,
    status: IntegrationReleaseStatus,
    detail: Optional[str] = None,
    blocked: bool = False,
) -> None:
    data = load_evidence()
    data[component] = {
        "status": status.value,
        "recorded_at": _now(),
        "detail": detail,
        "blocked": blocked,
    }
    save_evidence(data)


def get_component_status(component: str) -> Optional[str]:
    entry = load_evidence().get(component)
    if not entry:
        return None
    return entry.get("status")
